  
flows:
  onPush:
  - log: "${event.author} pushed ${event.commitId} to ${event.project}/${event.repository}"
                      
triggers:
- github:
    type: push
    useInitiator: true
    entryPoint: onPush
    
